# environments/conda.yml
name: loan-approval-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - azure-ai-ml==1.23.0
    - azure-identity
    - mlflow==2.12.0
    - azureml-mlflow
    - scikit-learn==1.4.0
    - pandas==2.2.0
    - numpy==1.26.0
    - pyodbc
    - matplotlib
    - seaborn
